# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1)),
                ('url', models.URLField()),
                ('data', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Data for POST')),
                ('headers', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'API Tasks',
            },
        ),
    ]
