# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=100, unique=True)),
                ('method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1)),
                ('url', models.URLField()),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Data for POST')),
                ('headers', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'API Tasks',
            },
        ),
    ]
