# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161203_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitask',
            name='callsign',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
